import Login from "../components/Pages/Home/Login";
import "../styles/globals.css";

import { headers } from "next/headers";
import { redirect } from "next/navigation";
import getSession from "./getSessionon";
import Index from "../components/Pages/Account/Index"


export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function Home() {
  const session = await getSession(headers().get('cookie') ?? '');
  return (
    <div>
      <main className="container flex-col flex-center ">
       {!session && <Login />}

      </main>
      {session && <Index session={session}/>}

    </div>
  );
}

// export async function getServerSideProps(context) {
//   const { query } = context;
//   const session = await getSession({ req: context.req });
//   const isError = session?.user?.email;
//   if (session && !isError?.includes("error")) {
//     return {
//       redirect: {
//         destination: "/account",
//         permanent: false,
//       },
//     };
//   }
//   if (isError) {
//     query.error = isError;
//   }
//   return {
//     props: { session, query },
//   };
// }
