import "../styles/globals.css";

import Footer from "../components/Layouts/Home/Footer";
import Navigation from "../components/Layouts/Home/Navigation";
// Components

// Header medata
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
export default function RootLayout({ children }) {
  // const route = children.props.childProp.segment;

  return (
    <html lang="en">
      <body className="h-screen min-h-screen flex justify-between flex-col bg-[#f7fcfd]">
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
[];
