import "../styles/globals.css";

import Footer from "../components/Layouts/Home/Footer";
import Navigation from "../components/Layouts/Home/Navigation";
// Components

// Header medata
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
export default function RootLayout({ children }) {
  // const route = children.props.childProp.segment;

  return (
    <html lang="en">
      <body className=" min-h-screen flex  flex-col bg-[#f7fcfd] relative">
        <Navigation />
        <div className="mt-32 mb-48">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
[];
