import "../styles/globals.css";

import { Session } from 'next-auth'
import { headers } from 'next/headers'
import AuthContext from "./AuthContext";

// Components
import Footer from "../components/Layouts/Home/Footer";
import Navigation from "../components/Layouts/Home/Navigation";
import getSession from "./getSessionon";

import AuthProtector from "./AuthProtector"
import Link from "next/link";
import Button from "../components/Forms/Buttons/Default";

// Header medata
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
// Session


// Layout 
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {

  const session = await getSession(headers().get('cookie') ?? '');



  return (
    <html lang="en">
      <body className=" min-h-screen flex  flex-col bg-[#f7fcfd] relative">

        <AuthContext session={session}>

          <Navigation session={session} />
          {/* Non-session */}
          {!session && <div className="mb-48 mt-36">
            {children}
          </div>}

          {/* Session */}
          {session && (<main className="container relative z-50 mt-36 mb-36">

            {session?.role == "admin" && <div className="flex p-5 mb-4 bg-gray-100 shadow-xl gap-x-2 rounded-xl">
              <div>
                <h2 className="mb-3 text-lg">Admin panel</h2>
                <Link href="/account/admin/create"><Button text="Създай оферта" theme="green" className="p-4 mb-2 text-sm" /></Link>
              </div>
            </div>}
            {children}</main>)}
          <Footer />

        </AuthContext>
      </body>
    </html>
  );
}
[];
