import Login from "../components/Pages/Home/Login";
import "../styles/globals.css";

import Head from "next/head";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Home() {
  return (
    <div>
      <Head>
        <title>Login page</title>
        <meta
          name="description"
          content="Your personal finance statement app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container flex-col flex-center ">
        <Login />
      </main>
    </div>
  );
}

// export async function getServerSideProps(context) {
//   const { query } = context;
//   const session = await getSession({ req: context.req });
//   const isError = session?.user?.email;
//   if (session && !isError?.includes("error")) {
//     return {
//       redirect: {
//         destination: "/account",
//         permanent: false,
//       },
//     };
//   }
//   if (isError) {
//     query.error = isError;
//   }
//   return {
//     props: { session, query },
//   };
// }
